### ISSUE TITLE
webpack打包后,线上环境遇到问题

### ISSUE THREAD

**Issue by main2017** [stackjie/vue-pull-to#1]
你好,你的vue-pull-to简单实用,但是我遇到了问题. 在线下用一切正常, 但是用webpack打包后线上环境bottom-load-method和top-load-method事件都没有触发,

**Comment by stackjie** [comment]
能否提供具体的使用示例的代码

**Comment by main2017** [comment]
.house-list
    pull-to(
      class="scroll",
      :top-load-method="refresh",
      :bottom-load-method="searchMore",
      :bottom-config="btmCfg"
      )
      ul: li(v-for="item in houses")
        house-item(:house="item")
        .split(v-show="houses.length > 1")

data () {
    return {
      beforeScroll: true,
      pullup: true,
      btnShow: true,
      page: 1,
      btmCfg: {
        doneText: '加载成功'
      }
    }
  },

  watch: {
    postEnd(bol) {
      if (bol && this.loaded) {
        this.loaded('done')
      }
    },
    pageEnd (bol) {
      if (bol && this.loaded) {
        this.btmCfg.doneText = '白扯了,木有数据了...'
        this.loaded('done')
      }
    }
  },
  methods: {
    searchMore(loaded) {
      this.loaded = loaded
      if (this.hasMove) { return }
      if (this.pageEnd) {
        loaded('done')
        return
      }

      this.page ++ // 上拉改变page,请求后面页码的数据
      this.$store.dispatch('getHouses', {
        pageNum: this.page,
        pageSize: PAGE_SIZE,
        province: this.currentCity.province,
        city: this.currentCity.city
      })
      this.hasMove = false
    },
    refresh (loaded) {
      loaded('done')
    },

**Comment by main2017** [comment]
我发现了, webpack打包之后, 用express配置了本地服务,启动本地服务node prod.server.js ,项目运行起来 bottom-load-method和top-load-method事件也都没有触发,

**Comment by stackjie** [comment]
项目中有没有用fast click这个库

**Comment by main2017** [comment]
用了

**Comment by stackjie** [comment]
你好已经修复了，`npm install vue-pull-to@0.0.7 --save` 更新一下

**Comment by main2017** [comment]
好的,非常感谢,^_^
