### ISSUE TITLE
能不能把下拉回弹禁止掉

### ISSUE THREAD

**Issue by yangshan010** [stackjie/vue-pull-to#10]
在我的页面中用不到下拉刷新，然后在页面往下滑动的时候，会触发下拉回弹。这样就会导致页面无法正常的下拉。

**Comment by stackjie** [comment]
不用传`top-load-method`就可以了

**Comment by stackjie** [comment]
还是你想禁用的是下拉回弹的效果呢？

**Comment by yangshan010** [comment]
想禁用掉下拉回弹的效果，因为这个会原本网页的往下滑动冲突。导致页面无法正常的往下滑动

**Comment by stackjie** [comment]
好的晚上回去把接口加上

**Comment by yangshan010** [comment]
好的 谢谢了。上拉跟下拉的口子都加上就好了。

**Comment by shx1545** [comment]
我也希望有这个功能，提供禁用上拉或者下拉。

**Comment by stackjie** [comment]
已经支持了分别是`is-top-bounce`对应下拉回弹和`is-bottom-bounce`对应上拉回弹，设为`false`就能关闭回弹效果了😀
