### ISSUE TITLE
infinite-scroll与scroll均无法触发

### ISSUE THREAD

**Issue by nullest** [stackjie/vue-pull-to#14]
浏览器：Chrome 61
系统：Mac 10.12

**Comment by stackjie** [comment]
可以上一下示例代码吗

**Comment by nullest** [comment]
**template**

`<pull-to :top-load-method="get" :bottom-load-method="getMore" @infinite-scroll="test">
            <article v-for="item in list" :key="item._id">
                 ...
            </article>
        </pull-to>`

script method:
`test() {
                console.log('infinite')
            }`

**Comment by nullest** [comment]
top-load-method, bottom-load-method均可以正常执行，infinite-scroll及scroll事件却不行

**Comment by nullest** [comment]
知道原因了，你监听的是当前容器的事件，而不是整个body的

**Comment by stackjie** [comment]
😀
