### ISSUE TITLE
scroll 事件似乎不是很灵敏?

### ISSUE THREAD

**Issue by jimmyyao88** [stackjie/vue-pull-to#19]
首先 ，很棒的组件
对比了一下原生的onscroll 事件 和 组件提供的scroll事件，同时监听容器的scrollTop值，在响应速度上似乎有点差距 
见下图 这是原生onscroll事件 缓慢的滑动 中间的console 打印scrollTop的值，可以看到每次都是1px的加上去 
![nativescroll2](https://user-images.githubusercontent.com/7344857/32370955-ee7f4410-c05c-11e7-8d75-226d5ab46943.gif)
这是vue-pull-to的scroll 事件 缓慢的滑动后每次的最小插值都是2px 这就会导致在滚动事件上做一些监听动画会有明显的卡顿感
![pulltoscroll](https://user-images.githubusercontent.com/7344857/32371030-48b2e6e4-c05d-11e7-9f60-861ebff4c593.gif)
想知道怎样可以避免这个情况 ，或者作者能否指出 和原生onscroll做法的区别

**Comment by stackjie** [comment]
因为为了性能考虑，scroll事件会默认被截流掉，如果需要实时触发的话，把prop `is-throttle-scroll`设为false就可以了

**Comment by jimmyyao88** [comment]
thx @stackjie
