### ISSUE TITLE
咋没有 滚动事件呀,我想监听滚动,

### ISSUE THREAD

**Issue by main2017** [stackjie/vue-pull-to#2]
咋没有 滚动事件呀,我想监听滚动,最好能监听到 scrollTop的值
类似这样的
pull-to(
      class="detail-content",
      @scroll="scroll",
      v-if="house && info"
      )

**Comment by stackjie** [comment]
目前版本还没有加滚动事件的接口 晚上我回去补上

**Comment by main2017** [comment]
好的,

**Comment by stackjie** [comment]
滚动事件我已经加上了，默认会被截流如果想要实时触发请修改`is-throttle-scroll`prop接口，传的回调函数第一个参数为`event`对象，你可以通过`event.target`拿到滚动容器的dom对象来获取`scrollTop`属性
