### ISSUE TITLE
hello Why hasn't the small icon appear（为什么没有小图标出现呢）

### ISSUE THREAD

**Issue by Aliceco** [stackjie/vue-pull-to#20]
我看了一下文档也没有讲这么实现，我也看了案例是require('./assets/icon/iconfont')需要引入这个，我也试着在本地引入但是 因为我项目是有语法检查的 iconfont.js文件 过不了

**Comment by stackjie** [comment]
因为小图标没有封装在组件里，你可以参考example的代码加上

**Comment by Aliceco** [comment]
好的，其实主要是iconfont.js这个过不了语法检查，您有没有解决方法呢，还有就是非常搞笑您开源了这个组件

**Comment by stackjie** [comment]
图标目前是需要自己自定上去的😃

**Comment by Aliceco** [comment]
好的，谢谢

**Comment by stackjie** [comment]
@Aliceco 你可以把我的icon font文件下载下来用，或者用你自己的图标也可以的

**Comment by stackjie** [comment]
#4

**Comment by Aliceco** [comment]
非常感谢您
