### ISSUE TITLE
滑动页面空白

### ISSUE THREAD

**Issue by peizhuang** [stackjie/vue-pull-to#21]
发现了一个Bug,启用上拉加载更多时，在底部快速滑动会概率性出现页面空白。不好意思，不能提供截屏或录屏，您可以试试可以复现不。

**Comment by LeeRayno** [comment]
@peizhuang  你是不是 给你的容器加了-webkit-overflow-scrolling: touch;这个css?
例如这样： 
```bash 
// html
<div class="yourwrapper">
     <vue-pull-to>xxxxx</vue-pull-to>
</div>
```
```bash
// css
.yourwrapper{ -webkit-overflow-scrolling: touch; } 
```
我之前好像也有这种情况，好像就是这个引起的。他的.scroll-content 已经加了-webkit-overflow-scrolling: touch; 了。
