### ISSUE TITLE
拖动无法看到全部内容，拖一半又弹回去了

### ISSUE THREAD

**Issue by mehooo** [stackjie/vue-pull-to#24]
拖动无法看到全部内容，拖一半又弹回去了

**Comment by stackjie** [comment]
你好请参考这篇文章，然后修改你的issue，抱歉😔
[如何向开源项目提交无法解答的问题](https://zhuanlan.zhihu.com/p/25795393)
最好能提供能复现问题的代码给我或者gif截图 谢谢
