### ISSUE TITLE
上拉加载下拉刷新，iOS都没问题， 安卓下拉没问题 但是上拉加载没反应

### ISSUE THREAD

**Issue by yilanye** [stackjie/vue-pull-to#3]
上拉加载下拉刷新，iOS都没问题， 安卓下拉没问题 但是上拉加载没反应，写法和demo是一样的

**Comment by stackjie** [comment]
你好，麻烦提供一下使用的示例代码、手机型号、安卓版本、浏览器版本之类的，我自己的安卓手机是没问题的

**Comment by yilanye** [comment]
我找了好几台安卓手机试了试，没有问题了，之前是微信和QQ的内置浏览器的问题，这两个平台不行。。。嘻嘻

**Comment by stackjie** [comment]
我刚刚用自己的手机测了下安卓 微信 QQ的内置浏览器，没有问题呀😂

**Comment by Troland** [comment]
楼主，我测试了微信内置的浏览器试了好几台也是不行！测试了魅族Note2,小米6都不行。

**Comment by zhowiny** [comment]
试了好几款安卓手机都不行,最终找到原因..
![image](https://user-images.githubusercontent.com/13558007/31490988-6194f31e-af78-11e7-80ec-982cbd038b94.png)
这段代码在部分安卓机,大部分浏览器下即使到了底部 checkBottomReached()的值依然为false
scrollTop与offsetHeight相加比scrollHeight还小1px;
至于为什么安卓某些浏览器会有1px相差我暂时还没时间去深究

在PC端调试完全没有问题,苹果的safari下也没有问题
不知道为什么图片上传不了,等我传一个我项目的图

**Comment by stackjie** [comment]
@zhowiny 非常感谢
