### ISSUE TITLE
使用swiper组件会阻止swiper的滑动事件

### ISSUE THREAD

**Issue by liushangdev** [stackjie/vue-pull-to#32]
你好，用了vux里面的swiper组件，然后嵌套了您的这个组件，发现会阻止外层swiper组件的滑动事件，不知道该怎么处理。希望得到您的帮助，谢谢

**Comment by liushangdev** [comment]
不好意思已经解决了，好像是宽度没有设置100%的问题。

**Comment by main2017** [comment]
你的是怎么解决的呢，我的父元素上的touch事件也触发不了

**Comment by wenlongLei** [comment]
事件无法监听到啊，你怎么搞定的
