### ISSUE TITLE
安卓下，上拉加载 会出现拉不上去的问题。直接不发上拉。

### ISSUE THREAD

**Issue by zhuangjunkun** [stackjie/vue-pull-to#38]
安卓下，上拉加载 会出现拉不上去的问题。直接不发上拉。 这个是怎么回事  ios 不会有这个问题

**Comment by truexu0529** [comment]
我也遇到了 在chrome上 拉不上去了。。。

**Comment by zhuangjunkun** [comment]
把容器高度 设成100%  overflow 设置成 scroll 。。列表容器 最好是 固定高度 或者 100%的话 不溢出屏幕 你调试看看

**Comment by zhuangjunkun** [comment]
@truexu0529 把容器高度 设成100% overflow 设置成 scroll 。。列表容器 最好是 固定高度 或者 100%的话 不溢出屏幕 你调试看看
