### ISSUE TITLE
写的很棒，另外可否分享下示例的iconfont

### ISSUE THREAD

**Issue by shx1545** [stackjie/vue-pull-to#4]
我直接拷贝你的iconfont有点大了，里面是不是还有除了示例的其它图标，可否分享线上iconfont的那几个示例的图标。

另外还是要赞几句，写的真不错，灵活，简单，bug少，功能全，github上很难找。

如果能加上 自定义 滚动条，并且 提供监控滚动回掉函数，就完美了。

**Comment by stackjie** [comment]
[iconfont.zip](https://github.com/stackjie/vue-pull-to/files/1316446/iconfont.zip)
😀

**Comment by shx1545** [comment]
谢谢了
