### ISSUE TITLE
手机上 内容过长，无法往下滚动查看内容

### ISSUE THREAD

**Issue by fashman** [stackjie/vue-pull-to#45]
如题！
![image](https://user-images.githubusercontent.com/12974473/36957757-a83e578c-2071-11e8-936e-943a47e9cf33.png)

Travel的内容很多很长，
用了 插件后只能查看第一屏，超出部分不能滚动查看了

**Comment by deffwe** [comment]
同样遇到这个问题，有答案吗

**Comment by dingww** [comment]
我也遇到这个问题，在开发者手机模拟器上可以滚动，到真机上就无法滚动了，不知道什么原因

**Comment by codingSuperIdiot** [comment]
这个问题是因为你滚动内容的外部容器没有设置高度

**Comment by F-loat** [comment]
#38
