### ISSUE TITLE
致所有用这个库的开发者

### ISSUE THREAD

**Issue by stackjie** [stackjie/vue-pull-to#49]
这个库好久没有维护了 最近可能抽时间来解决一下issues整理一下代码 坑了好多人抱歉233，有什么意见直接在这留言🐶

**Comment by xygahs0801** [comment]
支持，最近用到，目前找到的最好的一个

**Comment by 949961306** [comment]
oppor7  手机，用这个插件下拉动画会有很明显的卡顿效果，总共有3个页面，数据多的那个页面(一次接收40k左右的json)下拉动画卡顿特别严重，能达到5-10秒不回弹，其余两个页面没事。。这个怎么解。。。。。。。。

**Comment by 999946** [comment]
电脑谷歌浏览器打开手机模式无法触发下拉刷新

**Comment by MukaidoManaka** [comment]
上下拉 加载/刷新 的问题，怎么都拉不动，事件是触发了的，可是没卵用啊

**Comment by kid1412621** [comment]
pc 端，有随页面滑动的页脚，这种场景怎么解决
