### ISSUE TITLE
不好意思，提个需求常见哈。

### ISSUE THREAD

**Issue by veaba** [stackjie/vue-pull-to#6]
1、上拉刷新的时候，希望满足一定的阈值情况下，才会触发该事件，群友推荐下该组件，发现挺精简的。然而不可避免的发现一个我本想避免的问题。发现在滑动组件超过满屏高度下，不在顶部pull down，而是在滑动组件内部去下拉，发现会触发该下拉事件，这显然不太理想，下拉的时候。
![qq 20170920132741](https://user-images.githubusercontent.com/8652596/30628235-a8802726-9e07-11e7-85c6-5afa55ec7e0b.jpg)

**Comment by stackjie** [comment]
上拉加载如果需要一定的阈值才去触发的话用`bottom-load-method`这个prop接口，上拉下拉这两个接口的阀值都是可配置的，后面那个问题不是很理解

**Comment by shx1545** [comment]
我用的没任何问题，你最后那句问题在于你高度 没有设置 100%吧

**Comment by veaba** [comment]
@shx1545 你好，你说的是pull-to 组件的直接父级吗？
下图是pull-to 的父级设置了高度100%
![image](https://user-images.githubusercontent.com/8652596/30674891-a8f19750-9eaf-11e7-93c2-6e54f0bca19c.png)

下图是高度未到顶，在模拟器上，按住下拉，会触发事件
![image](https://user-images.githubusercontent.com/8652596/30674855-745b48b0-9eaf-11e7-8f6a-a0fbd4b1f750.png)

@stackjie  感谢答复。我表述可能有问题，这里纠正下，意思是：下拉动作（在顶部往下拖的动作，top-load-method | 顶部下拉时执行的方法），在pull-to 组件上 按住下拉，就会触发，不管是不是阈值设定多，一在上面下拉就会触发，但实际情况需求是，需要看到顶部的导航栏才会下拉执行事件。否则，用户使用手势往下拉滚动到底部的时候就会加载，这样的话，假如页面很长，用户就回不到顶部了。

如果还不太理解的我意思的话，稍后我可以做个录屏啊
