### ISSUE TITLE
你好  怎么可以重置一下列表数据

### ISSUE THREAD

**Issue by silverpeng** [stackjie/vue-pull-to#7]
比如说我改变一个接口的参数,不刷新当前页面的情况下,重置一下,这个组件的数据

**Comment by stackjie** [comment]
列表数据是你自己用`v-for`控制渲染的，你要刷新数据的话把调用ajax更新数据的方法传给`top-load-method`或者`bottom-load-method`或者放在相应的事件里，注意看下文档 😀  不知道有没有理解对你的问题😁

**Comment by silverpeng** [comment]
我的意思是  手动触发下拉刷新,不停的切换列表数据

**Comment by stackjie** [comment]
列表数据是由外部你自己来渲染的组件不参与，你想手动去刷新列表数据的话你就在外部重新请求一下接口刷新数据就可以呀😅

**Comment by silverpeng** [comment]
嗯,非常感谢,对了,对于列表跳转之后,返回时滚动条位置的还原, 您有有什么解决方法吗?

**Comment by stackjie** [comment]
@silverpeng  用Vue的`keep-alive`缓存你的列表组件就可以了，去看下Vue的文档

**Comment by silverpeng** [comment]
😄  不能的  keep-alive 只能保存数据信息, 并不能保存滚动条位置的,方便的话可以加您的qq吗?

**Comment by stackjie** [comment]
`keep-alive`是缓存整个组件，是可以解决你的问题的  qq:547363398
