### ISSUE TITLE
希望不要把 下拉刷新的动画加到 scroll 元素上，这样在开发中会有很多麻烦，因为我必须刻意的让其他元素设置 z-index 来避免上拉加载的文字和图标不显示出来

### ISSUE THREAD

**Issue by jiankafei** [stackjie/vue-pull-to#70]

**Comment by tiaod** [comment]
同意啊，如果标题栏是透明的，那个文字就保持显示了
![image](https://user-images.githubusercontent.com/7500825/51537059-6deaca00-1e88-11e9-9454-d5dda71c6a89.png)

**Comment by tiaod** [comment]
@jiankafei 为什么close了？你解决了吗

**Comment by jiankafei** [comment]
我打算，按照它的原理自己写一个，所以close

**Comment by jiankafei** [comment]
@tiaod 不过有个办法可以临时解决，就是自己在外面包一层，然后 overflow: hidden
